Repository RahulRimal/ccib_front, pull requests merged in 2024-06, with the labels that each got.

#8 [Feature] Added dashboard components
  src/App.jsx
  src/components/Charts/AnalyticsChart.jsx
  src/components/Drawer.jsx
  src/components/QuickDetailsCard.jsx
  src/components/RankSlider.jsx
  src/components/Tables/UserDetailsTable.jsx
  src/pages/Dashboard.jsx
  src/pages/UserProfile.jsx
  src/pages/dashboard/Dashboard.jsx
  src/pages/dashboard/components/QuickDetailsCard.jsx
Labels: feature

#12 [Feature] Added landing page
  package-lock.json
  package.json
  src/App.jsx
  src/components/Drawer.jsx
  src/components/Footer.jsx
  src/pages/SignIn.jsx
  src/pages/landing_page/LandingPage.jsx
  src/pages/landing_page/components/MainBanner.jsx
  src/pages/landing_page/components/Navbar.jsx
  src/pages/landing_page/components/News.jsx
  src/pages/landing_page/components/PayentmentModuleCard.jsx
Labels: feature

#14 [Feature] Added add form for all the models
  package-lock.json
  package.json
  src/App.jsx
  src/components/Button.jsx
  src/components/Drawer.jsx
  src/components/Footer.jsx
  src/components/Forms/BaseForm.jsx
  src/components/Forms/BlackListApplicationForm.jsx
  src/components/Forms/BlackListForm.jsx
  src/components/Forms/CheckboxField.jsx
  src/components/Forms/Fields/CheckboxField.jsx
  src/components/Forms/Fields/ImageInput.jsx
  src/components/Forms/Fields/InputField.jsx
  src/components/Forms/Fields/OptionField.jsx
  src/components/Forms/Fields/PasswordField.jsx
  src/components/Forms/Fields/RadioField.jsx
  src/components/Forms/Fields/TextAreaField.jsx
  src/components/Forms/InquiryForm.jsx
  src/components/Forms/InstallmentForm.jsx
  src/components/Forms/LoanAccountForm.jsx
  src/components/Forms/LoanApplicationForm.jsx
  src/components/Forms/SecurityDeposit.jsx
  src/components/TabButtons.jsx
  src/components/ToolTip.jsx
  src/custom_hooks/useFetch.jsx
  src/features/formTabsSlice.jsx
  src/pages/EmployeeProfile.jsx
  src/pages/LoanForm.jsx
  src/pages/SignIn.jsx
  src/pages/UserProfile.jsx
  src/pages/base_form/FormsBasePage.jsx
  src/pages/base_form/data.jsx
  src/pages/base_form/schemas.jsx
  src/store.js
Labels: feature

#15 [Enhacement] updating form application forms
  src/components/Backdrop.jsx
  src/components/Forms/AddUserForm.jsx
  src/components/Forms/BaseForm.jsx
  src/components/Forms/InquiryForm.jsx
  src/components/Forms/LoanAccountForm.jsx
  src/components/Forms/LoanApplicationForm.jsx
  src/components/Forms/SecurityDeposit.jsx
  src/pages/base_form/FormsBasePage.jsx
Labels: enhancement

#7 [Feature] Implemented authentication
  package-lock.json
  package.json
  src/App.jsx
  src/components/Drawer.jsx
  src/features/authSlice.jsx
  src/pages/Dashboard/components/IncomeChart.jsx
  src/pages/Home.jsx
  src/pages/SignIn.jsx
Labels: feature

#16 [Enhacement] added form validation
  src/components/Forms/AddUserForm.jsx
  src/components/Forms/BaseForm.jsx
  src/components/Forms/Fields/CheckboxField.jsx
  src/components/Forms/Fields/ErrorMessage.jsx
  src/components/Forms/Fields/InputField.jsx
  src/components/Forms/Fields/InputTitle.jsx
  src/components/Forms/Fields/OptionField.jsx
  src/components/Forms/Fields/RadioField.jsx
  src/components/Forms/Fields/TextAreaField.jsx
  src/components/Forms/InstallmentForm.jsx
  src/components/Forms/LoanAccountForm.jsx
  src/components/Forms/SecurityDeposit.jsx
  src/pages/Dashboard/Dashboard.jsx
Labels: enhancement

#17 [Feature] updating advanced filter forms and pages
  src/App.jsx
  src/components/FilterForm.jsx
  src/components/LoanFilterForm.jsx
  src/components/Tables/BaseTable.jsx
  src/components/Tables/ClassificationTable.jsx
  src/custom_hooks/useFetchTable.jsx
  src/pages/CompanyPage.jsx
  src/pages/Dashboard/components/IncomeChart.jsx
  src/pages/FinancePage.jsx
  src/pages/LoanApplicatinPage.jsx
  src/pages/LoansPage.jsx
  src/pages/UsersPage.jsx
Labels: feature

#19 [Feature] Added api interceptor
  src/api_service.js
  src/custom_hooks/useFetchTable.jsx
  src/features/authSlice.jsx
  src/pages/UserProfile.jsx
  src/pages/UsersPage.jsx
Labels: feature

#18 [Enhacement] add validation on filter form and updating filter form for pages
  src/components/FilterForm.jsx
  src/components/Forms/BaseForm.jsx
  src/components/Tables/BaseTable.jsx
  src/custom_hooks/useFetch.jsx
  src/pages/CompanyPage.jsx
  src/pages/FinancePage.jsx
  src/pages/LoanApplicatinPage.jsx
  src/pages/LoansPage.jsx
  src/pages/UsersPage.jsx
Labels: enhancement

#20 [Enhancement] Made it to auto refresh the access token in case of expiration
  src/api_service.js
  src/pages/LoanApplicatinPage.jsx
  src/pages/SignIn.jsx
  src/pages/UsersPage.jsx
Labels: enhancement

#22 [Bugfix] Fixed layout issue
  src/App.jsx
  src/layout.jsx
  subs.md
Labels: Bugfix :wrench:

#23 [Feature]Added News section and update footer css
  .eslintrc.json
  src/components/Footer.jsx
  src/components/Forms/Fields/InputField.jsx
  src/components/Forms/Fields/InputTitle.jsx
  src/pages/landing_page/LandingPage.jsx
  src/pages/landing_page/components/MainBanner.jsx
  src/pages/landing_page/components/News.jsx
Labels: Feature :rocket:

#26 [Refactor] minor changes in input and select fields
  src/components/Forms/Fields/InputField.jsx
  src/components/Forms/Fields/OptionField.jsx
  src/pages/SignIn.jsx
Labels: refactor

#25 [Enhancement] Refactored filtering code
  src/api_service.js
  src/components/Button.jsx
  src/components/FilterForm.jsx
  src/components/Tables/BaseTable.jsx
  src/custom_hooks/useFetchTable.jsx
  src/helpers.js
  src/pages/FinancePage.jsx
  src/pages/LoanApplication.jsx
  src/pages/LoanApplicationPage.jsx
  src/pages/UserProfile.jsx
  src/pages/UsersPage.jsx
Labels: Enhancement :sparkles:
